#!/bin/sh

action=$(gum choose "Show schedule" "Add an event" "Remove an event" "Update an event")

if [ "$action" = "Show schedule" ]
then
    option=$(gum choose "today" "this week" "given day" "week beginning..")

    if [ "$option" = "today" ]
    then
        kallen day
    elif [ "$option" = "this week" ]
    then
        kallen week
    else
        date=$(gum input --placeholder "DD/MM/YYYY")
        if [ "$option" = "given day" ]
        then
            kallen day "$date"
        else
            kallen week "$date"
        fi
    fi
elif [ "$action" = "Add an event" ]
then
    date=$(gum input --placeholder "DD/MM/YYYY")
    time=$(gum input --placeholder "20:04")
    desc=$(gum input --placeholder "really interesting description")
    kallen add --desc "$desc" --date "$date" -t "$time"
    kallen day --date "$date"
elif [ "$action" = "Remove an event" ]
then
    date=$(gum input --placeholder "DD/MM/YYYY")
    kallen day --date "$date"
    echo "Choose event: "
    idx=$(gum input --placeholder "8")
    kallen del --date "$date" -i "$idx"
    kallen day --date "$date"
else 
    date=$(gum input --placeholder "DD/MM/YYYY")
    kallen day --date "$date"
    echo "Choose event: "
    idx=$(gum input --placeholder "8")
    time=$(gum input --placeholder "20:04")
    desc=$(gum input --placeholder "really interesting description")
    kallen update --date "$date" -i "$idx" --desc "$desc" -t "$time"
    kallen day --date "$date"
fi


